let quotes: [[String: Any]] = [
    ["quote": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar"],
    ["quote": "You are what you do, not what you say you do.", "author": "Carl Jung"],
    ["quote": "Small deeds done are better than great deeds planned.", "author": "Peter Marshall"],
    ["quote": "The man who removes a mountain begins by carrying away small stones.", "author": "William Faulkner"],
    ["quote": "Keep away from people who try to belittle your ambitions. Small people always do that. The really great people make you feel that you, too, can become great.", "author": "Mark Twain"],
    ["quote": "You cannot be lonely if you like the person you're alone with.", "author": "Louisa Adams"],
    ["quote": "People may doubt what you say, but they will believe what you do.", "author": "Lewis Cass"],
    ["quote": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius"],
    ["quote": "Only put off until tomorrow what you are willing to die having left undone.", "author": "Pablo Picasso"],
    ["quote": "If you spend too much time thinking about a thing, you’ll never get it done.", "author": "Bruce Lee"],
    ["quote": "Every day do something that will inch you closer to a better tomorrow.", "author": "Doug Firebaugh"],
    ["quote": "The elevator to success is out of order. You’ll have to use the stairs… one step at a time.", "author": "Joe Girard"],
    ["quote": "I’d rather regret the things I’ve done than regret the things I haven’t done.", "author": "Lucille Ball"],
    ["quote": "A journey of a thousand miles begins with a single step.", "author": "Lao Tzu"],
    ["quote": "A year from now you will wish you had started today.", "author": "Unknown"],
    ["quote": "Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending.", "author": "Unknown"],
    ["quote": "Life is like riding a bicycle. To keep your balance you must keep moving.", "author": "Albert Einstein"],
    ["quote": "The beginning is always today.", "author": "Mary Shelley"],
    ["quote": "Reflect upon your present blessings, of which every man has many — not on your past misfortunes, of which all men have some.", "author": "Charles Dickens"],
    ["quote": "Be happy in the moment, that’s enough. Each moment is all we need, not more.", "author": "Mother Teresa"],
    ["quote": "Spending today complaining about yesterday won’t make tomorrow any better.", "author": "Unknown "],
    ["quote": "However vast the darkness, we must supply it with our own light.", "author": "Stanley Kubrick"],
    ["quote": "When eating fruit, remember the one who planted the tree.", "author": "Vietnamese Proverb "],
    ["quote": "I was complaining that I had no shoes till I met a man who had no feet.", "author": "Confucius "],
    ["quote": "Enjoy the little things, for one day you may look back and realize they were the big things.", "author": "Robert Brault"],
    ["quote": "Everything has beauty, but not everyone sees it. ", "author": "Confucius"],
    ["quote": "This is a wonderful day. I have never seen this one before.", "author": "Maya Angelou"],
    ["quote": "It’s actually cool to be positive and optimistic and idealistic. It’s cool to see yourself doing beautiful, great things.", "author": "Tom DeLonge"],
    ["quote": "The last of the human freedoms is to choose one’s attitude in any given set of circumstances.", "author": "Victor Frankl"],
    ["quote": "If you don’t like something, change it. If you can’t change it, change your attitude. Don’t complain.", "author": "Maya Angelou"],
    ["quote": "Almost every successful person begins with two beliefs: the future can be better than the present, and I have the power to make it so.", "author": "David Brooks"],
    ["quote": "If you believe it will work out, you will see opportunities. If you believe it won’t, you will see obstacles.", "author": "Wayne Dyer"],
    ["quote": "Create the highest, grandest vision possible for your life, because you become what you believe.", "author": "Oprah Winfrey"],
    ["quote": "One day or day one. You decide.", "author": "Unknown"],
    ["quote": "Never make a permanent decision based on a temporary storm. No matter how raging the billows are today, remind yourself, ‘This too shall pass’!", "author": "T.D. Jakes"],
    ["quote": "Decision is the ultimate power. Decisions shape destiny.", "author": "Tony Robbins"],
    ["quote": "The only workout you’ll regret is the one that didn’t happen.", "author": "Unknown"],
    ["quote": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Henry David Thoreau"],
    ["quote": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "author": "Aristotle"],
    ["quote": "People with goals succeed because they know where they’re going.", "author": "Earl Nightingale"],
    ["quote": "You have to have the bad days to appreciate the good ones.", "author": "Unknown"],
    ["quote": "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", "author": "Winston Churchill"],
    ["quote": "If you change the way you look at things, the things you look at change.", "author": "Wayne Dyer"],
    ["quote": "Every day above earth is a good day.", "author": "Ernest Hemingway"],
    ["quote": "Be happy with what you have while working for what you want.", "author": "Helen Keller"],
    ["quote": "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.", "author": "Helen Keller"],
    ["quote": "Don't cry because it's over; smile because it happened.", "author": "Dr. Seuss"],
    ["quote": "Happiness will never come to those who fail to appreciate what they already have.", "author": "Buddha"],
    ["quote": "Every morning we are born again. What we do today is what matters most.", "author": "Buddha"],
    ["quote": "Believe nothing, no matter where you read it, or who said it, no matter if I have said it, unless it agrees with your own reason and your own common sense.", "author": "Buddha"],
    ["quote": "Teach this triple truth to all: A generous heart, kind speech, and a life of service and compassion are the things which renew humanity.", "author": "Buddha"],
    ["quote": "Nothing is permanent.", "author": "Buddha"],
    ["quote": "Set your heart on doing good. Do it over and over again and you will be filled with joy.", "author": "Buddha"],
    ["quote": "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", "author": "Buddha"],
    ["quote": "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", "author": "Buddha"],
    ["quote": "Happiness consists more in small conveniences or pleasures that occur every day, than in great pieces of good fortune that happen but seldom to a man in the course of his life.", "author": "Benjamin Franklin"],
    ["quote": "There is no path to happiness; happiness is the path.", "author": "Buddha "],
    ["quote": "A happy life consists not in the absence, but in the mastery of hardships.", "author": "Helen Keller "],
    ["quote": "Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.", "author": "Buddha"],
    ["quote": "We all smile in the same language.", "author": "Unknown"],
    ["quote": "Spread love everywhere you go. Let no one ever come to you without leaving happier.", "author": "Mother Teresa"],
    ["quote": "You will face many defeats in life, but never let yourself be defeated.", "author": "Maya Angelou"],
    ["quote": "Smooth seas do not make skillful sailors.", "author": "African Proverb"],
    ["quote": "If you find a path with no obstacles, it probably doesn’t lead anywhere.", "author": "Unknown "],
    ["quote": "Nobody’s going to win all the time. On the highway of life you can’t always be in the fast lane.", "author": "Haruki Murakami"],
    ["quote": "The harder the battle, the sweeter the victory.", "author": "Les Brown"],
    ["quote": "Only in the darkness can you see the stars.", "author": "Martin Luther King Jr."],
    ["quote": "In three words I can sum up everything I’ve learned about life. It goes on.", "author": "Robert Frost "],
    ["quote": "The best way out is through.", "author": "Robert Frost"]
]
