let quotes: [[String: Any]] = [
    ["quote": "You don’t have to be great to start, but you have to start to be great.", "author": "Zig Ziglar"],
    ["quote": "You are what you do, not what you say you do.", "author": "Carl Jung"],
    ["quote": "Small deeds done are better than great deeds planned.", "author": "Peter Marshall"],
    ["quote": "The man who removes a mountain begins by carrying away small stones.", "author": "William Faulkner"],
    ["quote": "Keep away from people who try to belittle your ambitions. Small people always do that. The really great people make you feel that you, too, can become great.", "author": "Mark Twain"],
    ["quote": "You cannot be lonely if you like the person you're alone with.", "author": "Louisa Adams"],
    ["quote": "People may doubt what you say, but they will believe what you do.", "author": "Lewis Cass"],
    ["quote": "It does not matter how slowly you go as long as you do not stop.", "author": "Confucius"],
    ["quote": "Only put off until tomorrow what you are willing to die having left undone.", "author": "Pablo Picasso"],
    ["quote": "If you spend too much time thinking about a thing, you’ll never get it done.", "author": "Bruce Lee"],
    ["quote": "Every day do something that will inch you closer to a better tomorrow.", "author": "Doug Firebaugh"],
    ["quote": "The elevator to success is out of order. You’ll have to use the stairs… one step at a time.", "author": "Joe Girard"],
    ["quote": "I’d rather regret the things I’ve done than regret the things I haven’t done.", "author": "Lucille Ball"],
    ["quote": "A journey of a thousand miles begins with a single step.", "author": "Lao Tzu"],
    ["quote": "A year from now you will wish you had started today.", "author": "Unknown"],
    ["quote": "Though no one can go back and make a brand new start, anyone can start from now and make a brand new ending.", "author": "Unknown"],
    ["quote": "Life is like riding a bicycle. To keep your balance you must keep moving.", "author": "Albert Einstein"],
    ["quote": "The beginning is always today.", "author": "Mary Shelley"],
    ["quote": "Reflect upon your present blessings, of which every man has many - not on your past misfortunes, of which all men have some.", "author": "Charles Dickens"],
    ["quote": "Be happy in the moment, that’s enough. Each moment is all we need, not more.", "author": "Mother Teresa"],
    ["quote": "Spending today complaining about yesterday won’t make tomorrow any better.", "author": "Unknown "],
    ["quote": "However vast the darkness, we must supply it with our own light.", "author": "Stanley Kubrick"],
    ["quote": "When eating fruit, remember the one who planted the tree.", "author": "Vietnamese Proverb "],
    ["quote": "I was complaining that I had no shoes till I met a man who had no feet.", "author": "Confucius "],
    ["quote": "Enjoy the little things, for one day you may look back and realize they were the big things.", "author": "Robert Brault"],
    ["quote": "Everything has beauty, but not everyone sees it. ", "author": "Confucius"],
    ["quote": "This is a wonderful day. I have never seen this one before.", "author": "Maya Angelou"],
    ["quote": "It’s actually cool to be positive and optimistic and idealistic. It’s cool to see yourself doing beautiful, great things.", "author": "Tom DeLonge"],
    ["quote": "The last of the human freedoms is to choose one’s attitude in any given set of circumstances.", "author": "Victor Frankl"],
    ["quote": "If you don’t like something, change it. If you can’t change it, change your attitude. Don’t complain.", "author": "Maya Angelou"],
    ["quote": "Almost every successful person begins with two beliefs: the future can be better than the present, and I have the power to make it so.", "author": "David Brooks"],
    ["quote": "If you believe it will work out, you will see opportunities. If you believe it won’t, you will see obstacles.", "author": "Wayne Dyer"],
    ["quote": "Create the highest, grandest vision possible for your life, because you become what you believe.", "author": "Oprah Winfrey"],
    ["quote": "One day or day one. You decide.", "author": "Unknown"],
    ["quote": "Never make a permanent decision based on a temporary storm. No matter how raging the billows are today, remind yourself, ‘This too shall pass’!", "author": "T.D. Jakes"],
    ["quote": "Decision is the ultimate power. Decisions shape destiny.", "author": "Tony Robbins"],
    ["quote": "The only workout you’ll regret is the one that didn’t happen.", "author": "Unknown"],
    ["quote": "What you get by achieving your goals is not as important as what you become by achieving your goals.", "author": "Henry David Thoreau"],
    ["quote": "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", "author": "Aristotle"],
    ["quote": "People with goals succeed because they know where they’re going.", "author": "Earl Nightingale"],
    ["quote": "You have to have the bad days to appreciate the good ones.", "author": "Unknown"],
    ["quote": "The pessimist sees difficulty in every opportunity. The optimist sees opportunity in every difficulty.", "author": "Winston Churchill"],
    ["quote": "If you change the way you look at things, the things you look at change.", "author": "Wayne Dyer"],
    ["quote": "Every day above earth is a good day.", "author": "Ernest Hemingway"],
    ["quote": "Be happy with what you have while working for what you want.", "author": "Helen Keller"],
    ["quote": "When one door of happiness closes, another opens; but often we look so long at the closed door that we do not see the one which has been opened for us.", "author": "Helen Keller"],
    ["quote": "Don't cry because it's over; smile because it happened.", "author": "Dr. Seuss"],
    ["quote": "Happiness will never come to those who fail to appreciate what they already have.", "author": "Buddha"],
    ["quote": "Every morning we are born again. What we do today is what matters most.", "author": "Buddha"],
    ["quote": "Believe nothing, no matter where you read it, or who said it, no matter if I have said it, unless it agrees with your own reason and your own common sense.", "author": "Buddha"],
    ["quote": "Teach this triple truth to all: A generous heart, kind speech, and a life of service and compassion are the things which renew humanity.", "author": "Buddha"],
    ["quote": "Nothing is permanent.", "author": "Buddha"],
    ["quote": "Set your heart on doing good. Do it over and over again and you will be filled with joy.", "author": "Buddha"],
    ["quote": "Health is the greatest gift, contentment the greatest wealth, faithfulness the best relationship.", "author": "Buddha"],
    ["quote": "Do not dwell in the past, do not dream of the future, concentrate the mind on the present moment.", "author": "Buddha"],
    ["quote": "Happiness consists more in small conveniences or pleasures that occur every day, than in great pieces of good fortune that happen but seldom to a man in the course of his life.", "author": "Benjamin Franklin"],
    ["quote": "There is no path to happiness; happiness is the path.", "author": "Buddha "],
    ["quote": "A happy life consists not in the absence, but in the mastery of hardships.", "author": "Helen Keller "],
    ["quote": "Thousands of candles can be lighted from a single candle, and the life of the candle will not be shortened. Happiness never decreases by being shared.", "author": "Buddha"],
    ["quote": "We all smile in the same language.", "author": "Unknown"],
    ["quote": "Spread love everywhere you go. Let no one ever come to you without leaving happier.", "author": "Mother Teresa"],
    ["quote": "You will face many defeats in life, but never let yourself be defeated.", "author": "Maya Angelou"],
    ["quote": "Smooth seas do not make skillful sailors.", "author": "African Proverb"],
    ["quote": "If you find a path with no obstacles, it probably doesn’t lead anywhere.", "author": "Unknown "],
    ["quote": "Nobody’s going to win all the time. On the highway of life you can’t always be in the fast lane.", "author": "Haruki Murakami"],
    ["quote": "The harder the battle, the sweeter the victory.", "author": "Les Brown"],
    ["quote": "Only in the darkness can you see the stars.", "author": "Martin Luther King Jr."],
    ["quote": "In three words I can sum up everything I’ve learned about life. It goes on.", "author": "Robert Frost "],
    ["quote": "The best way out is through.", "author": "Robert Frost"],
    ["quote": "For God so loved the world that he gave his one and only Son, that whoever believes in him shall not perish but have eternal life.", "author": "John 3:16"],
    ["quote": "I can do all this through him who gives me strength.", "author": "Philippians 4:13"],
    ["quote": "‘For I know the plans I have for you,’ declares the Lord, ‘plans to prosper you and not to harm you, plans to give you hope and a future.’", "author": "Jeremiah 29:11"],
    ["quote": "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", "author": "Romans 8:28"],
    ["quote": "Trust in the Lord with all your heart and lean not on your own understanding; in all your ways submit to him, and he will make your paths straight.", "author": "Proverbs 3:5-6"],
    ["quote": "But seek first his kingdom and his righteousness, and all these things will be given to you as well.", "author": "Matthew 6:33"],
    ["quote": "The Lord is my shepherd, I lack nothing.", "author": "Psalm 23:1"],
    ["quote": "Love is patient, love is kind. It does not envy, it does not boast, it is not proud. It does not dishonor others, it is not self-seeking, it is not easily angered, it keeps no record of wrongs. Love does not delight in evil but rejoices with the truth. It always protects, always trusts, always hopes, always perseveres.", "author": "1 Corinthians 13:4-7"],
    ["quote": "But those who hope in the Lord will renew their strength. They will soar on wings like eagles; they will run and not grow weary, they will walk and not be faint.", "author": "Isaiah 40:31"],
    ["quote": "But the fruit of the Spirit is love, joy, peace, forbearance, kindness, goodness, faithfulness, gentleness and self-control. Against such things there is no law.", "author": "Galatians 5:22-23"],
    ["quote": "For it is by grace you have been saved, through faith-and this is not from yourselves, it is the gift of God-not by works, so that no one can boast.", "author": "Ephesians 2:8-9"],
    ["quote": "Cast all your anxiety on him because He cares for you.", "author": "1 Peter 5:7"],
    ["quote": "Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", "author": "Joshua 1:9"],
    ["quote": "For where two or three gather in my name, there am I with them.", "author": "Matthew 18:20"],
    ["quote": "Rejoice always, pray continually, give thanks in all circumstances; for this is God’s will for you in Christ Jesus.", "author": "1 Thessalonians 5:16-18"],
    ["quote": "The Lord bless you and keep you; the Lord make his face shine on you and be gracious to you; the Lord turn his face toward you and give you peace.", "author": "Numbers 6:24-26"],
    ["quote": "Peace I leave with you; my peace I give you. I do not give to you as the world gives. Do not let your hearts be troubled and do not be afraid.", "author": "John 14:27"],
    ["quote": "Do not be anxious about anything, but in every situation, by prayer and petition, with thanksgiving, present your requests to God. And the peace of God, which transcends all understanding, will guard your hearts and your minds in Christ Jesus.", "author": "Philippians 4:6-7"],
    ["quote": "But the Lord is faithful, and he will strengthen you and protect you from the evil one.", "author": "2 Thessalonians 3:3"],
    ["quote": "Jesus looked at them and said, 'With man this is impossible, but with God all things are possible.'", "author": "Matthew 19:26"],
    ["quote": "Therefore do not worry about tomorrow, for tomorrow will worry about itself. Each day has enough trouble of its own.", "author": "Matthew 6:34"],
    ["quote": "Let us not become weary in doing good, for at the proper time we will reap a harvest if we do not give up.", "author": "Galatians 6:9"],
    ["quote": "And we know that in all things God works for the good of those who love him, who have been called according to his purpose.", "author": "Romans 8:28"],
    ["quote": "For I am convinced that neither death nor life, neither angels nor demons, neither the present nor the future, nor any powers, neither height nor depth, nor anything else in all creation, will be able to separate us from the love of God that is in Christ Jesus our Lord.", "author": "Romans 8:38-39"],
    ["quote": "Commit to the Lord whatever you do, and he will establish your plans.", "author": "Proverbs 16:3"],
    ["quote": "May the God of hope fill you with all joy and peace as you trust in him, so that you may overflow with hope by the power of the Holy Spirit.", "author": "Romans 15:13"],
    ["quote": "Finally, brothers and sisters, whatever is true, whatever is noble, whatever is right, whatever is pure, whatever is lovely, whatever is admirable-if anything is excellent or praiseworthy-think about such things.", "author": "Philippians 4:8"],
    ["quote": "Therefore encourage one another and build each other up, just as in fact you are doing.", "author": "1 Thessalonians 5:11"],
    ["quote": "Have I not commanded you? Be strong and courageous. Do not be afraid; do not be discouraged, for the Lord your God will be with you wherever you go.", "author": "Joshua 1:9"],
    ["quote": "For I know the plans I have for you, declares the Lord, plans for welfare and not for evil, to give you a future and a hope.", "author": "Jeremiah 29:11"],
    ["quote": "Perform your obligatory duty, because action is indeed better than inaction.", "author": "Bhagavad Gita 3:8"],
    ["quote": "You have a right to perform your prescribed duties, but you are not entitled to the fruits of your actions.", "author": "Bhagavad Gita 2:47"],
    ["quote": "Whatever happened, happened for the good. Whatever is happening, is happening for the good. Whatever will happen, will also happen for the good.", "author": "Bhagavad Gita 2:47"],
    ["quote": "Those who see action in inaction and inaction in action are truly wise amongst humans.", "author": "Bhagavad Gita 4:18"],
    ["quote": "The soul is neither born, nor does it die, nor is it that having once existed, it ceases to exist.", "author": "Bhagavad Gita 2:20"],
    ["quote": "The mind is restless and difficult to restrain, but it is subdued by practice.", "author": "Bhagavad Gita 6:35"],
    ["quote": "Reshape yourself through the power of your will.", "author": "Bhagavad Gita 2:7"],
    ["quote": "Those who restrain their senses, and are of a balanced mind, are intent on the welfare of all beings, attain to God.", "author": "Bhagavad Gita 5:25"],
    ["quote": "Set thy heart upon thy work, but never on its reward.", "author": "Bhagavad Gita 2:47"],
    ["quote": "The wise see knowledge and action as one; they see truly.", "author": "Bhagavad Gita 5:4"]
]
